title: Cocov
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/"
url: "https://cocov.dev"

plugins:
  - "jekyll-github-metadata"
  - "jekyll-redirect-from"
  - "jekyll-last-modified-at"
  - "jekyll-toc"

last-modified-at:
  date-format: '%b %d, %Y'

repository: cocov-ci/docs

exclude:
  - script/
  - .github/

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
